name: Deploy loan-service

on:
  push:
    paths:
      - 'Loans/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        working-directory: Loans
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          POSTGRES_HOST : ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT : ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER : ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD : ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB : ${{ secrets.POSTGRES_DB }}
          REDIS_HOST : ${{ secrets.REDIS_HOST }}
          REDIS_PORT : ${{ secrets.REDIS_PORT }}
          REDIS_KEY : ${{ secrets.REDIS_KEY }}
          SERVICE_BUS_CONNECTION_STRING : ${{ secrets.SERVICE_BUS_CONNECTION_STRING }}
          LOG_QUEUE : ${{ secrets.LOG_QUEUE }}
          LOAN_QUEUE : ${{ secrets.LOAN_QUEUE }}
          ENCRYPTION_KEY : ${{ secrets.ENCRYPTION_KEY }}
    
        working-directory: Loans
        run: |
          pytest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: loan-service
          slot-name: Production
          publish-profile: ${{ secrets.LOAN_PUBLISH_PROFILE }}
          package: ./Loans
